### ISSUE TITLE
Wishlist: render messages.WARNING/ERROR/... distincly

### ISSUE THREAD

**Issue by Talkless** [django-admin-bootstrapped/django-admin-bootstrapped#116]
Currently, if messages.warning(), messages.critical() are added manually in view (for example in SomeAdmin.change_view()) they are all rendered inside:

```
<div class="alert alert-info">
```

So, warning and critical messages appear just like "successfully saved" info messages. They are hard to notice.

I am aware that `<li class="warning">` could be used to style manually, but still, they are in same peaceful blue "alert-info" div...

**Comment by lyndon-decor** [comment]
@xrmx https://far-offmui-x-data-grid.github.io/dpRAz4qwtqxWOSLPuFG4bj/
