### ISSUE TITLE
Scrollable menu

### ISSUE THREAD

**Issue by lopst** [django-admin-bootstrapped/django-admin-bootstrapped#169]
When a menu is displayed on a filter, if the list size is larger than the screen size, you can not select all items.

It can be solved by adding a class in the file filter.html

changing:
<li class = "dropdown-header">
by:
<li class="dropdown-header scrollable-menu">

and adding "scrollable-menu" to css file:

.scrollable-menu {
     height: auto;
     max-height: 250px;
     overflow-x: hidden;
}

Cheers!

**Comment by xrmx** [comment]
@lopst have you any chance to try the suggestion above? thanks
