### ISSUE TITLE
overrides.css property makes form-group with input-group-addon too short

### ISSUE THREAD

**Issue by nando1** [django-admin-bootstrapped/django-admin-bootstrapped#172]
I'm curious as to why this [property](https://github.com/django-admin-bootstrapped/django-admin-bootstrapped/blob/master/django_admin_bootstrapped/static/admin/css/overrides.css#L14) is in overrides.css

With height: 28px; 
![Before](http://i.imgur.com/plUdAbO.png)

Without:
![After](http://i.imgur.com/bfM3FS5.png)

**Comment by xrmx** [comment]
Care to share the code to reproduce it? That line has been there forever, no clue why it's here :)

**Comment by nando1** [comment]
I had this show up in my actual project which had other apps that may have conflicted.

But it still happened when I made a quick test project (simple model with 2 fields), and django-admin-bootstrapped as the only other app.

I then modified your fieldset.html file (around line 40) so that I could add the input-group-addon to the fields:

    <div class="input-group">
        {% dab_field_rendering field.field %}
        <span class="input-group-addon">
            <span class="glyphicon-calendar glyphicon"></span>
        </span>
    </div>
