### ISSUE TITLE
custom css for all of admin

### ISSUE THREAD

**Issue by awol** [django-admin-bootstrapped/django-admin-bootstrapped#173]
Hi,
I have been trying to customise the CSS for the admin site with varying success.

I have implemented custom AdminForms, using the Media class (as it happens actually overriding the media property for my purposes, but the Media class worked as well) to communicate my custom CSS to the forms. That works fine.

I also use a custom AdminSite and, likewise, define a Media class with my custom CSS. To this custom AdminSite, I register all my forms, plus a few models from the standard site (User, Group). However the non customised admin forms (User and Group) as well as the supporting pages, (index, applications, logout etc) ignore this custom CSS.

The solution I found was twofold. First in the file django_admin_bootstrapped/templates/admin/base.html I think there should be a `{{ media.css }}` inserted in the "extrastyle" block. This propagates quite nicely since most of the derived templates call `{{ block.super }}`. Second in the function `each_context` inside sites.py, one needs to add a key for the "media" attribute to the dict that is returned. I did not really want to patch Django, so for my purpose I just wrote an override function for this in my custom AdminSite.

With these two changes in place it works better. I am happy with overriding the `each_context` function. Is it sensible to put the media.css patch in to this project?

Cheers,
Philip

Actually just checking has shown that, login and confirm action (at least) are still broken even with my changes above... (more to check)

**Comment by xrmx** [comment]
Hello Philip, both of the changes you are proposing should be discussed upstream in the Django project itself. We are not going to add more delta especially if we can avoid it :) I think you are over engineering a bit, why mess with the admin classes when you can override the templates? Closing since this is not the right place to discuss upstream changes. Thanks.

**Comment by awol** [comment]
Happy to push it upstream, understood about the delta.

As for classes vs templates, I think the django design (and hence I appreciate your point about pushing the discussion upstream) is such that Media classes are the right way to get custom css into the output and its just that they are being ignored for some (but not other) of the Admin classes.

Thanks for the update
