### ISSUE TITLE
CheckboxSelectMultiple styles poorly

### ISSUE THREAD

**Issue by joelburton** [django-admin-bootstrapped/django-admin-bootstrapped#174]
If I have a m2m field and switch the widget to using CheckboxSelectMultiple, the styling looks very poor--it uses the same bulleted-list style as the default Django admin UI, but looks a bit worse as the CSS makes the checkbox vertically higher than expected. This is the same whether I use the django-bootstrap3 rendered or not.

(Note that if I make a form manually using django-bootstrap3 with a CheckboxSelectMultiple field, it appears in a more bootstrap-appearing form)

**Comment by xrmx** [comment]
Thanks for reporting! The fact that we render in a different way from the original with django-bootstrap3 renderer is really lame. Will take a look at it.

**Comment by xrmx** [comment]
@joelburton Are you getting something like this right? http://imgur.com/7iaZilP

**Comment by xrmx** [comment]
@joelburton Latest git should be a lot better, looking forward for your feedback!

**Comment by joelburton** [comment]
(just saw this requested but, yes, it looks much better. thanks!)
