### ISSUE TITLE
Model pages obscured 

### ISSUE THREAD

**Issue by adamteale** [django-admin-bootstrapped/django-admin-bootstrapped#179]
Hi Guys,

I imagine that this is not a bug but perhaps something that's a bit quirky on my side, but I am getting some weird results:

![captura de pantalla 2015-02-24 a las 11 54 19](https://cloud.githubusercontent.com/assets/7489774/6351676/23d23d04-bc1c-11e4-8f4f-6615b21be64f.jpg)

The strange thing is that running the development server through django the page renders fine (with the Filter and Action menus above the content), but when they run on the production server this happens.

Any ideas?

Thanks

Adam

**Comment by xrmx** [comment]
Look at your browser console for 404, missing collect static possibly?

**Comment by adamteale** [comment]
xrmx thanks for writing back - unfortunately there are no errors appearing, just strange rendering.

Any ideas as to what else I could try?

**Comment by xrmx** [comment]
Which browser is this btw? which version of django-admin-bootstrapped?

**Comment by adamteale** [comment]
This is on both Chrome and Safari. It was happening on an earlier version, so I updated yesterday to the latest, and the issue remains.

I wonder if it is something related to my django install?

Is there any template that could effect the rendering of django-admin-bootstrapped?

Cheers!

**Comment by xrmx** [comment]
Il 24/02/2015 16:12, adamteale ha scritto:
> This is on both Chrome and Safari. It was happening on an earlier version, so I
> updated yesterday to the latest, and the issue remains.
>
> I wonder if it is something related to my django install?
>
> Is there any template that could effect the rendering of django-admin-bootstrapped?

Try to move django_admin_bootstrapped app on top of INSTALLED APPS. If that does 
not work could you please dump the rendered html and upload it on a gist so i 
can take a look please?

**Comment by adamteale** [comment]
thanks a lot, I'll do that now

**Comment by xrmx** [comment]
@adamteale has this been resolved for you?

**Comment by adamteale** [comment]
@xrmx Unfortunately the problems remains.

I have just ave the html from the rendered page and put it onto gist:
https://gist.github.com/adamteale/611b7e599b2036eb97a8

Is that what you need?

Thanks for your help!

**Comment by xrmx** [comment]
This loads perfectly fine both in runserver and with uwsgi [1], any chance one of your other apps are overwriting some css in admin? Use the debug tools for your browser to find out who is responsible for that white rectangle.
[1]http://imgur.com/w0l0nQs

**Comment by adamteale** [comment]
Thanks @xrmx for looking into it! I have no idea about what else could be doing that, but I will keep digging.
Many thanks for your effort!

**Comment by xrmx** [comment]
@adamteale i've completely overlooked the fact that the action goes below the bar when it does not fit, while it look fine on firefox, it looks crap on at least chrome. I'll take a look at it, thanks for reporting!

**Comment by xrmx** [comment]
@adamteale Could you please give latest git a try please? Not that i've fixed something related to your issue but maybe it helps.

**Comment by adamteale** [comment]
@xrmx Ahh good to know that it is of some use to you! 
I will grab the latest git now and let you know, thanks!

**Comment by adamteale** [comment]
Newbie question - how do I install a commit via pip? Thanks!

**Comment by xrmx** [comment]
```
pip install git+https://github.com/django-admin-bootstrapped/django-admin-bootstrapped.git
```
should do the trick

**Comment by adamteale** [comment]
@xrmx apologies for not getting back to you over the weekend!

I ran the above pip command but it seems that it has version 2.3.3 installed - however i think i see that there is a 2.3.4 available on github.

Here is what pip spits out:

  Cloning https://github.com/django-admin-bootstrapped/django-admin-bootstrapped.git to /var/folders/2y/qvv0j3s53xv4p8dklkdwv5tm0000gn/T/pip-agNjve-build
  Running setup.py (path:/var/folders/2y/qvv0j3s53xv4p8dklkdwv5tm0000gn/T/pip-agNjve-build/setup.py) egg_info for package from git+https://github.com/django-admin-bootstrapped/django-admin-bootstrapped.git
    
Requirement already satisfied (use --upgrade to upgrade): django-admin-bootstrapped==2.3.3 from git+https://github.com/django-admin-bootstrapped/django-admin-bootstrapped.git in ./venv/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./venv/lib/python2.7/site-packages/setuptools-12.2-py2.7.egg (from django-admin-bootstrapped==2.3.3)
Requirement already satisfied (use --upgrade to upgrade): Django>=1.6 in ./venv/lib/python2.7/site-packages (from django-admin-bootstrapped==2.3.3)
Cleaning up...

**Comment by adamteale** [comment]
@xrmx apologies for not getting back to you over the weekend!

I see a change! It is still weird but a significant change in appearance:

![captura de pantalla 2015-03-02 a las 18 47 31](https://cloud.githubusercontent.com/assets/7489774/6451339/a656d664-c10c-11e4-962a-25597e1ed38b.jpg)

Any ideas??

Many thanks!

**Comment by xrmx** [comment]
Il 02/03/2015 22:48, adamteale ha scritto:
> @xrmx <https://github.com/xrmx> apologies for not getting back to you over the
> weekend!
>
> I see a change! It is still weird but a significant change in appearance:
>
> captura de pantalla 2015-03-02 a las 18 47 31
> <https://cloud.githubusercontent.com/assets/7489774/6451339/a656d664-c10c-11e4-962a-25597e1ed38b.jpg>
>
> Any ideas??

Which is your screen size? Are you sure you don't have any custom css that is 
interfering? The fact that the add button is grey indicates something is off.
Have you run a collectstatic after upgrading?

**Comment by adamteale** [comment]
@xrmx - i think we are getting somewhere now.

I did a collect static - but it did not seem to make a difference.

I took a look at the css files that are being loaded and found that if i disabled the code in the file static/admin/css/changelists.css and then refreshed the page - voila, the strange formatting disappeared! 
Then i reenabled that code, refreshed it, and the proper page formatting remained.
I don't understand why, but I am happy if it works.

I have noticed that the button "Select All" isn't available when the page loads, but after clicking the toggle all button checkbox in the table the button then does appear.

But it is all looking much better! 
Many thanks for your patience in trying to help me resolve the issue!

**Comment by xrmx** [comment]
Il 03/03/2015 17:18, adamteale ha scritto:
> I took a look at the css files that are being loaded and found that if i
> disabled the code in the file static/admin/css/changelists.css and then
> refreshed the page - voila, the strange formatting disappeared!
> Then i reenabled that code, refreshed it, and the proper page formatting remained.
> I don't understand why, but I am happy if it works.

Uhm that's interesting, let me try to reproduce that

> I have noticed that the button "Select All" isn't available when the page loads,
> but after clicking the toggle all button checkbox in the table the button then
> does appear.

That's how it is supposed to work, "select all" means select every object in the 
queryset.

> But it is all looking much better!
> Many thanks for your patience in trying to help me resolve the issue!

No problem! your report helped in making the code better

**Comment by xrmx** [comment]
@adamteale could you please pastebin the changelists.css you get served? Open it from the browser and paste it from there.

**Comment by xrmx** [comment]
@adamteale closing this, please reopen when / if you can share the offending changelists.css
