### ISSUE TITLE
2.3.4 breaks forms?

### ISSUE THREAD

**Issue by stugots** [django-admin-bootstrapped/django-admin-bootstrapped#183]
I'm running Django 1.6.10, Python 2.6.9, on OS X.

With django-admin-bootstrapped 2.3.3, admin forms display normally.

But with django-admin-bootstrapped 2.3.4, no fields are displayed. Every change or add form looks like this one. This happens in the latest versions of Safari and Firefox. 

Anyone else see this?

![screen shot 2015-03-13 at 2 27 06 pm](https://cloud.githubusercontent.com/assets/231148/6647594/4197b4bc-c98d-11e4-849f-4246728af483.png)

**Comment by xrmx** [comment]
Thanks for reporting! Indeed I've broken something with django 1.6. Will fix and release 2.3.5 tomorrow CEST time.

**Comment by xrmx** [comment]
Fixed in5ccdeea00b47e1c5f67a631df2afc98deac0d417, released  2.3.5 which should have already hit pypi. Thanks again and sorry for the issue!
