### ISSUE TITLE
update admin/base.html for Django 1.8

### ISSUE THREAD

**Issue by ttanner** [django-admin-bootstrapped/django-admin-bootstrapped#188]
admin/base.html has changed with Django 1.8
https://github.com/django/django/pull/3762/files

**Comment by xrmx** [comment]
Thanks for reporting. Unfortunately using a new context variable (has_permission) makes it difficult to handle compatibility with django 1.7. I'll try to sort something out.

**Comment by xrmx** [comment]
I think this has been fixed in:
3fca84c0c2fcc7bf91d2ba85d14726ca0182e4bd
Care to double check? Thanks!
