### ISSUE TITLE
TemplateDoesNotExist admin/includes/object_delete_summary.html

### ISSUE THREAD

**Issue by skolsuper** [django-admin-bootstrapped/django-admin-bootstrapped#194]
`admin/includes/object_delete_summary.html`

This template is referenced from `django_admin_bootstrapped/templates/admin/delete_selected_confirmation.html` and `django_admin_bootstrapped/templates/admin/delete_confirmation.html`.

It doesn't exist in django.contrib.auth.admin templates to fall back on either, maybe it was removed in a recent django?  Currently I'm using django 1.7.7

**Comment by xrmx** [comment]
Thanks for reporting. Which version of django-admin-bootstrapped are you using?

**Comment by xrmx** [comment]
It looks like you are using 2.5.0 which does not support django < 1.8. So please downgrade to 2.4.0 or upgrade django.

**Comment by skolsuper** [comment]
Okay my bad, thanks for the help.
