### ISSUE TITLE
AdminSite site title

### ISSUE THREAD

**Issue by drakkan** [django-admin-bootstrapped/django-admin-bootstrapped#195]
when using django-admin-bootstrapped site title in not customizable using AdminSite, take a look here please

 https://code.djangoproject.com/ticket/24740#comment:4

**Comment by xrmx** [comment]
If you look at the source code here you'll see how to override that
https://github.com/django-admin-bootstrapped/django-admin-bootstrapped/blob/master/django_admin_bootstrapped/templates/admin/base_site.html#L4

Please note that this feature is deprecated and has been removed from documentation. In 2.5.1 we'll switch to behave like upstream django.

**Comment by drakkan** [comment]
ok, I'll wait for 2.5.1 thanks

**Comment by xrmx** [comment]
@drakkan could you please check git master that works for you? thanks!

**Comment by drakkan** [comment]
it works now, thanks!
