### ISSUE TITLE
Can I somehow make navbar black?

### ISSUE THREAD

**Issue by d33tah** [django-admin-bootstrapped/django-admin-bootstrapped#196]
I read the README, but this question doesn't seem to be answered - is there a way to make navbar black using this package?

Also, I really like the look-and-feel of the project!

**Comment by xrmx** [comment]
You can but you have to do it yourself :) Customization can be done with the usual django way which is providing your own templates, so depending on which navbar you want black you have to provide base.html or base_site.html, see https://docs.djangoproject.com/en/1.8/ref/settings/#template-dirs

**Comment by jpimentel** [comment]
@d33tah probably you just need to override the needed css, if you just need to do color changes

**Comment by d33tah** [comment]
Thanks, creating the ```admin``` directory in my template directory and copying ```base.html``` there let me solved it. All that was left then was adding the ```navbar-inverse``` class to the navbar.
