### ISSUE TITLE
Popup not working in Django 1.8

### ISSUE THREAD

**Issue by wdbaruni** [django-admin-bootstrapped/django-admin-bootstrapped#199]
Hi
When I click on the plus sign next to a Foreignkey or M2M fields, the same page display the view for the related model instead of rendering a popup. 
I tried installing in Django 1.7 and the popup worked just fine, so it looks like compatibility issue with Django 1.8.

**Comment by xrmx** [comment]
Thanks for reporting. Which version of django-admin-bootsrapped are you using? With django 1.8.x please use 2.5.0, templates have changed quite a bit.

**Comment by wdbaruni** [comment]
Thank you for your quick response. I upgraded now to Django 1.8.2 and the problem was solved. Previously I was on Django 1.8.1
Both cases I was using django-admin-bootstrapped 2.5.0

**Comment by xrmx** [comment]
If it is solved, let's close this issue then. Thanks!
