### ISSUE TITLE
change_password.html shouldn't require user.username

### ISSUE THREAD

**Issue by joshkel** [django-admin-bootstrapped/django-admin-bootstrapped#200]
To support User models that don't provide a `username` field, `templates/admin/auth/user.html` shouldn't get the `original.username` attribute.

This is the same issue as https://code.djangoproject.com/ticket/19056; the same fix (replacing `original.username` with `original`) works here.

**Comment by xrmx** [comment]
Do you mean `templates/admin/auth/login.html` and using `original.get_username` right?

**Comment by joshkel** [comment]
Sorry, I meant `templates/admin/auth/change_password.html`. Thanks.

Django uses `original` instead of `original.get_username`; see [here](https://code.djangoproject.com/ticket/19056), [here](https://github.com/django/django/commit/4c75344cc1d3c74ed73b7a8d6aab92a173afe8f5), and [here](https://github.com/django/django/blob/master/django/contrib/admin/templates/admin/auth/user/change_password.html). (I assume this is so that it respects overriding the User model's `__str__`.)

**Comment by xrmx** [comment]
Thanks for reporting btw :)
