### ISSUE TITLE
Redundant separators in change_password.html

### ISSUE THREAD

**Issue by joshkel** [django-admin-bootstrapped/django-admin-bootstrapped#201]
change_password.html puts `<span class="divider">/</span>` dividers in its breadcrumbs, but Bootstrap automatically adds dividers with a `li+li ::before` rule. As a result, duplicate dividers get added, looking something like this:

> Home / / App / / Users / / username / / Change password

A quick `grep` shows similar spans under `filer` templates (although I haven't actually viewed these in a browser to see if they're affected).

**Comment by xrmx** [comment]
Thanks for reporting, fixed and released 2.5.2 with the fix. Whilte at it i've cleaned up the html a bit to look more like other forms.

**Comment by joshkel** [comment]
Thank you.
