### ISSUE TITLE
filter_horizontal widget isn't bootstrapped (and is actually slightly broken)

### ISSUE THREAD

**Issue by walkerdb** [django-admin-bootstrapped/django-admin-bootstrapped#203]
Fields using the filter_horizontal option for an admin model field are rendered like this:

![filter_horizontal example](https://cloud.githubusercontent.com/assets/7026330/8344936/0358bc08-1ab6-11e5-87a8-d41d000febaf.PNG)

which has no bootstrap styling. In fact, it doesn't even look quite the same as its vanilla form, which should be this:

![django-admin-after](https://cloud.githubusercontent.com/assets/7026330/8345070/ecafddc2-1ab7-11e5-8375-889a83e5b734.png)

In the bootstrapped version the "add" arrows have been forced underneath the fields, instead of existing inline, which makes things a little more confusing from the user's perspective.

**Comment by xrmx** [comment]
Thanks for reporting! Yeah, django admin widgets tend to look quite crappy, will take a look at this. Any help with the needed css fixup would be much appreciated

**Comment by xrmx** [comment]
Fixed it a bit, not perfect but should be a lot more usable. Please give latest git a try.

**Comment by walkerdb** [comment]
That worked! Thanks for the fix. Now that I know where to look I may also try fiddling around with the css at some point to clear up some of the rough edges.
