### ISSUE TITLE
django1.6.11 with django-admin-bootstrapped 2.3.5 error

### ISSUE THREAD

**Issue by longkeng** [django-admin-bootstrapped/django-admin-bootstrapped#206]
I'm using django1.6.11 with django-admin-bootstrapped 2.3.5, but when running admin page, bellow of error is displayed.
``
Error during template rendering
In template /Library/Python/2.7/site-packages/django_admin_bootstrapped/templates/admin/base.html, error at line 89
no such column: django_content_type.name
``
But if test on django1.8 with new version of  django-admin-bootstrapped, error not be displayed.

**Comment by xrmx** [comment]
Thanks for reporting. It doesn't look like a django-admin-bootstrapped error though, it looks like more your db and your django installation are out of sync. Pretty sure we are not messing django ContentType attributes. Feel free to reopen if you have other logs that point to our code.

**Comment by longkeng** [comment]
Thanks for reply!
I'm sorry, that's my error related sync db.
