### ISSUE TITLE
In pagination, the current page is not highlighted

### ISSUE THREAD

**Issue by d33tah** [django-admin-bootstrapped/django-admin-bootstrapped#207]
Have a look there:

http://getbootstrap.com/components/#disabled-and-active-states

The current page has a ```<span class="this-page">``` that doesn't have a CSS attached to it. Perhaps making it an alias to ``active`` would solve this problem? Not knowing which page we're on is a bit confusing.

**Comment by xrmx** [comment]
Thanks for reporting and for the hints. Should be fixed in lastest git.

**Comment by reinout** [comment]
Could you make a new release, perhaps? 

I'd like this fix and I don't want a git master checkout in my production site :-)

**Comment by xrmx** [comment]
@reinout Need to take a closer look at #212 and #213 before cutting a new release. Hopefully before next week.

**Comment by reinout** [comment]
Ok, fine.

In the mean time I solved it by overriding the css file with the latest version in my site's static/admin folder, so there's no real rush.
