### ISSUE TITLE
Add RTL support for the 2.3.x branch

### ISSUE THREAD

**Issue by uda** [django-admin-bootstrapped/django-admin-bootstrapped#209]
I'm using an app based on Django 1.6, and it needs RTL, but the admin looks really bad with half RTL support.
Just add the conditional added style from master.

**Comment by xrmx** [comment]
Will merge the feature but django 1.6 is not maintained anymore upstream, possibly a good time to upgrade?

**Comment by uda** [comment]
Thanks.
It's an open source / open data project maintained by many volunteers, and I am just the devops, I can suggest, but that is where my part ends...

**Comment by xrmx** [comment]
Merged #210 as 779ca8d49eec67a615cc1a9eea2831c9b286e8a1 . Please double check that everything is fine and i'll release 2.3.6

**Comment by uda** [comment]
Installed from the branch and it looks fine.

**Comment by xrmx** [comment]
I've releases 2.3.6 to pypi you can upgrade your requirements.

**Comment by uda** [comment]
Thanks!
