### ISSUE TITLE
Stacked inline formset non-form and non-field errors not rendered properly

### ISSUE THREAD

**Issue by nothingelsematters7** [django-admin-bootstrapped/django-admin-bootstrapped#213]
Non-form errors now https://github.com/django-admin-bootstrapped/django-admin-bootstrapped/blob/master/django_admin_bootstrapped/templates/admin/edit_inline/stacked.html#L5:
```
{{ inline_admin_formset.formset.non_form_errors }}
```

Should be something like this
```
{% if inline_admin_formset.formset.non_form_errors %}
    <div class="alert alert-danger">
        {{ inline_admin_formset.formset.non_form_errors }}
    </div>
{% endif %}
```

Non-field errors now https://github.com/django-admin-bootstrapped/django-admin-bootstrapped/blob/master/django_admin_bootstrapped/templates/admin/edit_inline/stacked.html#L36:
```
{% if inline_admin_form.form.non_field_errors %}
    {{ inline_admin_form.form.non_field_errors }}
{% endif %}
```

Should be something like this:
```
          {% if inline_admin_form.form.non_field_errors %}
              <div class="alert alert-danger">
                {{ inline_admin_form.form.non_field_errors }}
              </div>
          {% endif %}
```

**Comment by xrmx** [comment]
Thanks for reporting. Which version of django / django-admin-bootstrapped are you using? Will take a look in the next few days.

**Comment by nothingelsematters7** [comment]
Django (1.8.2)
django-admin-bootstrapped (2.5.4)

I can even make a PR :-)

**Comment by xrmx** [comment]
@nothingelsematters7 next time a PR would make it easier for me, thanks :)
