### ISSUE TITLE
Missing 'Add another' link/button in inline formset

### ISSUE THREAD

**Issue by Wtower** [django-admin-bootstrapped/django-admin-bootstrapped#230]
Hello, congratulations for the nice project. I have an issue with using it. I suppose there must be something that I miss so apologies if this is the case.

This is the first time that I use it. I installed it properly with pip and added it in apps setting. I have not installed django-bootstrap3.

When opening a form to edit or add a record, and the form contains an inline, there is no 'Add another' link present. Additionally, there are several errors present in browser's inspector.

If you would like me to include more information regarding the errors or my admin code please let me know.

**Comment by xrmx** [comment]
Please report django version, d-a-b version and provide a screenshot for ui artifacts and c&p of inspector errors if caused by d-a-b.

**Comment by Wtower** [comment]
After spending my morning and much digging, it seems that there was another script that was messing with d-a-b. So my apologies for the inconvenience. I close the issue.
