### ISSUE TITLE
django1.9 password_reset templates don't render

### ISSUE THREAD

**Issue by hellpanderrr** [django-admin-bootstrapped/django-admin-bootstrapped#233]
Because of 
>ssi and url template tags are removed from the future template tag library.
https://docs.djangoproject.com/en/1.9/releases/1.9/#features-removed-in-1-9

[templates for password reset](https://github.com/django-admin-bootstrapped/django-admin-bootstrapped/tree/master/django_admin_bootstrapped/templates/registration) throw 
>TemplateSyntaxError at /accounts/password/reset/
'url' is not a valid tag or filter in tag library 'future'

**Comment by dudanogueira** [comment]
I believe the same goes to the logout.

**Comment by hellpanderrr** [comment]
Have a working version here: https://github.com/hellpanderrr/django-admin-bootstrapped-1.9-compatible

**Comment by xrmx** [comment]
@hellpanderrr thanks, will check your changes

**Comment by Wtower** [comment]
+1

Looks good to me and worked as expected.
