### ISSUE TITLE
Using $ instead of jQuery in login.html

### ISSUE THREAD

**Issue by levic** [django-admin-bootstrapped/django-admin-bootstrapped#234]
See https://github.com/django-admin-bootstrapped/django-admin-bootstrapped/blob/master/django_admin_bootstrapped/templates/admin/login.html#L88

Every other usage of jquery as far as I can tell is wrapped with
```javascript
function($) {
    ...
})(jQuery);
```

This particular instance isn't; it causes errors if $ has been changed or jQuery.noConflict() has been used

**Comment by xrmx** [comment]
thanks for reporting, looking forward to a pull request fixing this.
