### ISSUE TITLE
filermedia' is not a registered tag library

### ISSUE THREAD

**Issue by darshit7** [django-admin-bootstrapped/django-admin-bootstrapped#239]
**I am using filer 1.0.6. But i got following error while try to uploading an image file. Please provide solution for this version.**

TemplateSyntaxError at /admin/filer/folder/

'filermedia' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_tree
admin_tree_list
admin_urls
aldryn_bootstrap3_tags
bootstrap
bootstrapped_goodies_tags
cache
cms_admin
cms_js_tags
cms_static
cms_tags
cms_wizard_tags
common_tags
conversejs
cp_tagfilters
cropping
filer_admin_tags
filer_image_tags
filer_tags
format_duration
forum_extras
future
highlight
i18n
in_list
isinstructor
l10n
load_helpdesk_settings
log
markdown_deux_tags
menu_tags
more_like_this
mptt_admin
mptt_tags
pagination_tags
saved_queries
sekizai_tags
static
staticfiles
tagfilters
thumbnail
ticket_to_link
tree_menu_tags
tz
user_admin_url

Request Method:     GET
Django Version:     1.9.1
Exception Type:     TemplateSyntaxError

**Comment by xrmx** [comment]
It looks like you are using django 1.9 which is not supported. Are you using django-cms too? django-admin-bootstrapped is not a good fit for a django-cms project. django-filter integration is not supported, patches to fix any issues are very welcome though.
