### ISSUE TITLE
Overridden admin templates are broken

### ISSUE THREAD

**Issue by gmircea** [django-admin-bootstrapped/django-admin-bootstrapped#249]
I have overridden a admin template in order to change the list view for only a specific model from my app.
That page isn't rendered properly, it's broken: the filters are rendered on top of the listing, not on the right.
For the other models, everything is ok, they don't have the template overridden.
I've used this: https://docs.djangoproject.com/en/1.9/ref/contrib/admin/#overriding-admin-templates
Basically, I've created the following directory structure: templates/admin/my_app/my_model, then copied the change_list.html file there, and added info to it.
In the overridden change_list.html template; I've printed some extra numeric fields at the bottom
Does anyone have a suggestion, do I need to do some additional configuration ?
![image](https://cloud.githubusercontent.com/assets/7654459/15805403/c8b3c024-2b31-11e6-9a1c-5379a6aa3957.png)

**Comment by xrmx** [comment]
Sorry, but if you have overriden a template then you are on you own. Btw you are referring to django 1.9 documentation while this app does not support django 1.9.

**Comment by gmircea** [comment]
Actually I'm using Django 1.8, that section is the same in 1.8 and 1.9.
Then maybe it's worth a mention in the documentation, that overriding is not supported.
Now, that I'm on my own, do you have any hints ? Where should I look for the trouble ? In the sources I mean...

Thanks and regards.

**Comment by xrmx** [comment]
Overriding templates should work just as fine as in plain django. Since you are using different templates that the one shipped with this project you cannot expect to support your templates.

**Comment by gmircea** [comment]
I found the solution, very simple.
My 'custom' template was only adding some very small amount of additional info to change_list.html, so basically it was the same structure and style as the original template + some aditions: basic HTML.
Before, as the source, I used the template from **contrib/admin/templates/admin**
The solution was to use the overridden template from **django_admin_bootstrapped/templates/admin**/change_list.html: so I copied this file in **templates/admin/my_app/my_model**, then I added my stuff in that file.
