### ISSUE TITLE
Required close button after validation failed

### ISSUE THREAD

**Issue by Dharmik8478** [django-admin-bootstrapped/django-admin-bootstrapped#250]
I am working on python 3.4 and django 1.9 .I didn't get a close button for the form whose validation failed in inline forms.Please give any solutions.

Thank You.

**Comment by xrmx** [comment]
Sorry, we don't support django 1.9 at the moment. Also we don't provide solutions, pull request fixing django 1.9 of course are welcome.

**Comment by Dharmik8478** [comment]
Please provide any solutions for django 1.8
