### ISSUE TITLE
Django 1.10 logout template

### ISSUE THREAD

**Issue by jameswinegar** [django-admin-bootstrapped/django-admin-bootstrapped#253]
We're using this for a project. Only problem we're seeing is the logout screen throws an exception.

Removing {% import urls from future %} in the template fixes the issue, but there are a lot of other changes required for submitting a good pull request.

**Comment by xrmx** [comment]
Thanks for the report, I'm not sure i understand why you are not opening a pull request though.

**Comment by jameswinegar** [comment]
#233 fixes this, but isn't in latest pypi release.

**Comment by eduardocalil** [comment]
Please, could you release a 2.5.8 version, so that you can get it into PyPi? Thanks.

**Comment by divick** [comment]
+1
