### ISSUE TITLE
Last item of inlines without add permission gets hidden

### ISSUE THREAD

**Issue by augustomen** [django-admin-bootstrapped/django-admin-bootstrapped#265]
If any inline has:

    def has_add_permission(self, *_):
        return False

No extra rows are displayed (correctly) but the last related object row gets the class `empty-form` ([stacked](https://github.com/django-admin-bootstrapped/django-admin-bootstrapped/blob/master/django_admin_bootstrapped/templates/admin/edit_inline/stacked.html#L13) or [tabular](https://github.com/django-admin-bootstrapped/django-admin-bootstrapped/blob/master/django_admin_bootstrapped/templates/admin/edit_inline/tabular.html#L31):

        class="...{% if forloop.last %} empty-form last-related{% endif %}"...

But Django default style for this class is hidden ([admin/css/forms.css](https://github.com/django/django/blob/master/django/contrib/admin/static/admin/css/forms.css#L498)).

Should this static file be overwritten?

**Comment by augustomen** [comment]
Sorry, this is clearly a conflict in Django 2+ (or possibly 1.10/1.11 - haven't checked out).

**Comment by pirm-in** [comment]
Oh nice, this issue has already been reported :)

It still happens in Django 3.1.6
I just observed the exact same behaviour. I would have guessed that something about the conditionals for adding the `empty-form` class is wrong. 

```
% if forloop.last and inline_admin_formset.has_add_permission %} empty-form{% endif %}
```

For some reason `empty-form` is added twice, once (correctly) to the `add-row` and and once to the last `form-row` (while the `add-row` is in fact the last row of the table in the DOM)
