### ISSUE TITLE
Django 2.2 support (render() got an unepected keyword argumen renderer)

### ISSUE THREAD

**Issue by guruganesh26** [django-admin-bootstrapped/django-admin-bootstrapped#266]
Hi,

I am using this library for my admin interface, i recently migrated from django 1.8 to 2.2, but this library not supporting 2.2? i received 'render() got an unepected keyword argumen renderer' this error.

Do you have any plan to support 2.2? or suggest me any relevant library

**Comment by xrmx** [comment]
Yes, use the upstream admin theme which is already responsive

**Comment by guruganesh26** [comment]
Can you please share the library link, which you mentioned? i googled but didn't find.
