### ISSUE TITLE
State of the project? Looks dead

### ISSUE THREAD

**Issue by guettli** [django-admin-bootstrapped/django-admin-bootstrapped#268]
This project looks dead. No updates since 2015.

Is there a feasible alternative?

**Comment by xrmx** [comment]
The defaut django admin theme?

**Comment by abidibo** [comment]
@guettli  you can try Django Baton, it's based on bootstrap 4.5 - https://github.com/otto-torino/django-baton/

**Comment by guettli** [comment]
Thank you for clarification.
