### ISSUE TITLE
Incompatibility with django-wysiwg-redactor

### ISSUE THREAD

**Issue by riccardo-forina** [django-admin-bootstrapped/django-admin-bootstrapped#74]

**Comment by nordbit** [comment]
Do not work anymore

**Comment by xrmx** [comment]
@nordbit: are you sure it is not this issue?
https://github.com/douglasmiranda/django-wysiwyg-redactor/issues/80
If not please open a new bug.

**Comment by nordbit** [comment]
It is. I used older version of redactor.
